### ISSUE TITLE
Problem with running CosmoGUI.py

### ISSUE THREAD

**Issue by ModeS7** [CosmoAI-AES/CosmoSim#116]
![Screenshot 2023-04-19 103313](https://user-images.githubusercontent.com/114737447/233018021-137f6e1f-2ea4-4cac-8ff7-eea2a5a49cb0.png)

**Comment by hgeorgsch** [comment]
This should be corrected, changing the method name to setModelMode in Controller.py.
Please verify and close the issue if it works, @ModeS7
