### ISSUE TITLE
Basesize or size variable in CosmoSim.h limits image size

### ISSUE THREAD

**Issue by kristlv1** [CosmoAI-AES/CosmoSim#118]
Images created from .csv file can not exceed the size of either basesize or size (or both) in CosmoSim.h.

Images created without .csv file does not produce this problem.

**Comment by hgeorgsch** [comment]
I have changed datagen.py to set basesize equal to size.  Previously only the latter was changed by the -Z option.
Could you check if this solves the problem @kristlv1 ?

FYI basesize is used to set the resolution; the GUI allows you to change both, to get the coarse resolution, even if it is displayed as a large image.  I cannot remember exactly how it is done.  The CLI does not support such coarse images, and I am not going to change that now.

**Comment by hgeorgsch** [comment]
BTW. THe change is made on develop.

**Comment by kristlv1** [comment]
The fix was also present in branch speedup-centring. Problem fixed for now.

**Comment by kristlv1** [comment]
Closed issue too quickly, was using the wrong branch. The problem still persist, when using csv file argument or not. -Z argument does not do anything when above 512. If -Z argument is higher, image will be 512x512 pixels. Problem on branch develop and branch speedup-centring.
