### ISSUE TITLE
Elliptical Lens Model

### ISSUE THREAD

**Issue by hgeorgsch** [CosmoAI-AES/CosmoSim#19]

**Comment by hgeorgsch** [comment]
What makes this difficult @kosmoben ?
Would we not be able to simply take an expression for psi and use the existing SIS code?
Yes, there is some concern about rotation, but if you give me psi, I can give it a try ...

**Comment by kosmoben** [comment]
Yupp, now that we sorted out the recursion relations I think it should in principle be SIS procedure. I’ll give you a psi…! :)

Good  psi for now!
-Ben

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hgeorgsch** [comment]
@kosmoben Is there a reasonably simple way to calculate the apparent position ($\nu=\xi/\chi$) for a given source position $\eta$?

And also for the first partial derivatives, if you have?  I have not seen what the CAS engine gives yet, but I would prefer a manual result if it is simple enough.

**Comment by kosmoben** [comment]
Not sure I got it:  do you mean if there is a reasonable way to calculate $\nu$ without finding the derivatives?

**Comment by kosmoben** [comment]
So, if I get you right you want someting like this, just for SIE?

![image](https://github.com/CosmoAI-AES/CosmoSim/assets/93264235/c5060383-b9c9-458d-99a6-11e821248c18)

**Comment by hgeorgsch** [comment]
Indeed.

**Comment by kosmoben** [comment]
I have written this somewhere. Would have to redo the proof to validate it

![image](https://github.com/CosmoAI-AES/CosmoSim/assets/93264235/dcdf3c26-09ab-4389-8561-ba68eece664a)

**Comment by kosmoben** [comment]
(I think it is correct)

**Comment by hgeorgsch** [comment]
This does not make sense; (3) adds an absolute value to a 2D vector.

**Comment by kosmoben** [comment]
Yes... They are all supposed to be vectors...

**Comment by hgeorgsch** [comment]
Then there must be a missing angle.  \Delta\eta is independent of \eta AFAICS but the direction cannot be independent of the direction of \eta.

**Comment by kosmoben** [comment]
Eta should also be written out in polar coordinates. Not sure it can be inverted for R and \phi (the polar coordinates), however.

Quite messy...Let me write it down in a more orderly fashion (helps my own thinking anyway)

**Comment by hgeorgsch** [comment]
Which equation? Oh is \phi the sum of the rotation of the lens and the angle of \eta?  Then it might work

**Comment by kosmoben** [comment]
This is where I got: https://www.overleaf.com/project/63f83f51927ba353e7b14f06

**Comment by kosmoben** [comment]
<img width="561" alt="image" src="https://github.com/CosmoAI-AES/CosmoSim/assets/93264235/571c923a-48ef-4144-a223-1ce56f0772e8">

<img width="562" alt="image" src="https://github.com/CosmoAI-AES/CosmoSim/assets/93264235/a4e82da4-ff85-4f07-a685-337940bb89f7">

**Comment by kosmoben** [comment]
In summary: The two equations 15 and 16 doesn't seem easy to invert :)

**Comment by hgeorgsch** [comment]
IOW.  This wasn't easy and is not going to be pretty!?

**Comment by hgeorgsch** [comment]
Check papers (see confluence) and find formulation matching the one above.  One seems to give the deflection formula separately, saving us the differentiation.

Once this is done, we can implement raytrace and sampled roulette.

**Comment by hgeorgsch** [comment]
This seems to be a good paper on SIE: https://academic.oup.com/mnras/article/442/1/428/1244014?login=true

**Comment by hgeorgsch** [comment]
First prototype available.  New and more specific issues: #159 #160 #161
